from __future__ import annotations

from abc import ABC, abstractmethod
from collections.abc import Iterable
import json
import re
from urllib.parse import urljoin, urlsplit, urlunsplit

import httpx
from bs4 import BeautifulSoup

from .model import ParsedPosting, PostingRef, norm_text


TP_ID = re.compile(r"(01000000-[0-9a-f-]{20,})", re.I)


def canonical_url(url: str) -> str:
    p = urlsplit(url)
    return urlunsplit((p.scheme, p.netloc, p.path, "", ""))


class SourceAdapter(ABC):
    code: str

    @abstractmethod
    def listing_urls(self) -> Iterable[str]:
        raise NotImplementedError

    @abstractmethod
    def parse_listing(self, html: str, base_url: str) -> list[PostingRef]:
        raise NotImplementedError

    @abstractmethod
    def parse_detail(self, html: str, url: str) -> ParsedPosting:
        raise NotImplementedError

    def discover(self, client: httpx.Client, limit: int) -> list[PostingRef]:
        out: dict[str, PostingRef] = {}
        for listing_url in self.listing_urls():
            response = client.get(listing_url)
            response.raise_for_status()
            before = len(out)
            for ref in self.parse_listing(response.text, str(response.url)):
                out.setdefault(ref.source_posting_id, ref)
                if len(out) >= limit:
                    return list(out.values())[:limit]
            if len(out) == before and out:
                break
        return list(out.values())[:limit]


class TheProtocolAdapter(SourceAdapter):
    code = "theprotocol"

    SITEMAP_URL = "https://static.theprotocol.it/sitemaps/CurrentOffers/SiteMapJobOffers1.xml"

    def listing_urls(self):
        yield self.SITEMAP_URL

    def parse_listing(self, html: str, base_url: str) -> list[PostingRef]:
        # CurrentOffers sitemap is a public discovery surface and avoids coupling
        # discovery to the Cloudflare-protected interactive listing.
        import xml.etree.ElementTree as ET
        found: dict[str, PostingRef] = {}
        root = ET.fromstring(html)
        for node in root.iter():
            if not node.tag.endswith("loc") or not node.text:
                continue
            url = canonical_url(node.text.strip())
            if "/szczegoly/praca/" not in url:
                continue
            match = TP_ID.search(url)
            if not match:
                continue
            sid = match.group(1)
            found[sid] = PostingRef(self.code, url, sid)
        return list(found.values())

    def parse_detail(self, html: str, url: str) -> ParsedPosting:
        soup = BeautifulSoup(html, "html.parser")
        h1 = soup.find("h1")
        if not h1:
            raise ValueError("PARSER_DRIFT: TheProtocol h1 missing")
        match = TP_ID.search(url)
        if not match:
            raise ValueError("TheProtocol source ID missing")
        company = _first_text(
            soup,
            [
                '[data-test="text-offerEmployer"]',
                '[data-testid="company-name"]',
                ".company-name",
            ],
        ) or _best_company_heading(soup, h1)
        text = soup.get_text("\n", strip=True)
        ai_derived = bool(re.search(r"wygenerowane przez AI|generated by AI", text, re.I))
        return ParsedPosting(
            source=self.code,
            source_posting_id=match.group(1),
            url=canonical_url(url),
            title=norm_text(h1.get_text(" ", strip=True)),
            company_mention=company,
            body_text=text,
            source_specific={"platform_ai_summary_present": ai_derived},
        )


class JustJoinItAdapter(SourceAdapter):
    code = "justjoinit"

    def listing_urls(self):
        yield "https://justjoin.it/job-offers/all-locations"
        for page in range(2, 31):
            yield f"https://justjoin.it/job-offers/all-locations?page={page}"

    def parse_listing(self, html: str, base_url: str) -> list[PostingRef]:
        soup = BeautifulSoup(html, "html.parser")
        found: dict[str, PostingRef] = {}
        for a in soup.find_all("a", href=True):
            href = a["href"]
            if "/job-offer/" not in href:
                continue
            url = canonical_url(urljoin(base_url, href))
            sid = url.rstrip("/").split("/")[-1]
            if not sid:
                continue
            found[sid] = PostingRef(self.code, url, sid)
        return list(found.values())

    def parse_detail(self, html: str, url: str) -> ParsedPosting:
        soup = BeautifulSoup(html, "html.parser")
        h1 = soup.find("h1")
        if not h1:
            raise ValueError("PARSER_DRIFT: JJIT h1 missing")
        sid = canonical_url(url).rstrip("/").split("/")[-1]
        company = _first_text(
            soup,
            ['[data-testid="company-name"]', ".company-name"],
        ) or _best_company_heading(soup, h1)
        skills = []
        for node in soup.select("[data-skill][data-level]"):
            skills.append({"skill": node.get("data-skill"), "level": node.get("data-level")})
        return ParsedPosting(
            source=self.code,
            source_posting_id=sid,
            url=canonical_url(url),
            title=norm_text(h1.get_text(" ", strip=True)),
            company_mention=company,
            body_text=soup.get_text("\n", strip=True),
            source_specific={"skill_expectations": skills},
        )


def _first_text(soup: BeautifulSoup, selectors: list[str]) -> str | None:
    for selector in selectors:
        node = soup.select_one(selector)
        if node:
            value = norm_text(node.get_text(" ", strip=True))
            if value:
                return value
    return None


def _best_company_heading(soup: BeautifulSoup, h1) -> str | None:
    blocked = {
        "job description", "tech stack", "requirements", "responsibilities",
        "nice to have", "benefits", "about the company", "o firmie",
    }
    for node in h1.find_all_next(["h2", "h3"]):
        value = norm_text(node.get_text(" ", strip=True))
        if value and value.casefold() not in blocked and len(value) <= 160:
            return value
    return None


ADAPTERS = {
    "theprotocol": TheProtocolAdapter(),
    "justjoinit": JustJoinItAdapter(),
}


def _jobposting_json_ld(soup: BeautifulSoup):
    """Return stable JobPosting structured data, excluding volatile presentation metadata."""
    candidates = []
    for node in soup.find_all("script", attrs={"type": "application/ld+json"}):
        raw = node.string or node.get_text()
        if not raw:
            continue
        try:
            value = json.loads(raw)
        except Exception:
            continue
        values = value if isinstance(value, list) else [value]
        for item in values:
            if isinstance(item, dict) and item.get("@type") == "JobPosting":
                candidates.append(item)
            if isinstance(item, dict) and isinstance(item.get("@graph"), list):
                candidates.extend(
                    x for x in item["@graph"]
                    if isinstance(x, dict) and x.get("@type") == "JobPosting"
                )
    if not candidates:
        return None
    item = candidates[0]
    stable_keys = (
        "title", "description", "qualifications", "skills", "responsibilities",
        "employmentType", "jobLocationType", "applicantLocationRequirements",
        "jobLocation", "baseSalary", "hiringOrganization", "industry",
        "experienceRequirements", "educationRequirements",
    )
    return {k: item[k] for k in stable_keys if k in item}


def _stable_sections(soup: BeautifulSoup):
    """Conservative fallback: only job-content sections, never full rendered page chrome."""
    wanted = {
        "job description", "responsibilities", "requirements", "nice to have",
        "tech stack", "benefits", "about the company", "about us",
    }
    out = {}
    headings = soup.find_all(["h2", "h3"])
    for heading in headings:
        name = norm_text(heading.get_text(" ", strip=True))
        if name.casefold() not in wanted:
            continue
        parts = []
        for node in heading.find_all_next():
            if node is heading:
                continue
            if getattr(node, "name", None) in ("h2", "h3"):
                break
            if getattr(node, "name", None) in ("p", "li", "h4"):
                text = norm_text(node.get_text(" ", strip=True))
                if text and text not in parts:
                    parts.append(text)
        out[name.casefold()] = parts
    return out
